/** @type {import('tailwindcss').Config} */
const v = (name) => `rgb(var(--${name}) / <alpha-value>)`;

export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  /** Light mode chính thức (Đợt A). Giữ `class` để token cũ `dark:` không kích hoạt nếu không gắn `.dark` lên html. */
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        sans: [
          '"Plus Jakarta Sans"',
          "-apple-system",
          "BlinkMacSystemFont",
          '"SF Pro Text"',
          '"Segoe UI"',
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "sans-serif",
        ],
        mono: [
          '"IBM Plex Mono"',
          "ui-monospace",
          "SFMono-Regular",
          '"SF Mono"',
          "Menlo",
          "Consolas",
          "monospace",
        ],
      },
      colors: {
        /** Semantic tokens — Operational Signal Design Tokens (v2). */
        ui: {
          background: v("background"),
          surface: v("surface"),
          "surface-muted": v("surface-muted"),
          "surface-sunken": v("surface-sunken"),
          text: v("foreground"),
          "text-muted": v("muted-foreground"),
          border: v("border"),
          "border-strong": v("border-strong"),
          input: v("input"),
          primary: v("primary"),
          "primary-hover": v("primary-hover"),
          "primary-fg": v("primary-foreground"),
          "primary-soft": v("primary-soft"),
          accent: v("accent"),
          focus: v("ring"),
          navy: v("brand-navy"),
          success: v("success"),
          "success-soft": v("success-soft"),
          warning: v("warning"),
          "warning-soft": v("warning-soft"),
          danger: v("danger"),
          "danger-soft": v("danger-soft"),
          info: v("info"),
          "info-soft": v("info-soft"),
          status: {
            "success-soft": v("success-soft"),
            "warning-soft": v("warning-soft"),
            "danger-soft": v("danger-soft"),
            "info-soft": v("info-soft"),
          },
          stage: {
            booking: v("stage-booking"),
            "at-warehouse": v("stage-at-warehouse"),
            docs: v("stage-docs"),
            done: v("stage-done"),
            history: v("stage-history"),
          },
          awb: v("foreground"),
        },
        wh: {
          tcs: v("wh-tcs"),
          "tcs-bar": v("wh-tcs-bar"),
          scsc: v("wh-scsc"),
          "scsc-bar": v("wh-scsc-bar"),
          tecs: v("wh-tecs"),
        },
        // Legacy aliases: dashboard.*, apple.*, ops.* (trỏ về ui.* tương ứng; xóa ở P2 khi grep = 0)
        dashboard: {
          canvas: v("background"),
          "canvas-dark": "#070B14",
          surface: v("surface"),
          "surface-dark": "#0F172A",
          primary: v("brand-navy"),
          "primary-dark": "#F8FAFC",
          muted: v("muted-foreground"),
          "muted-dark": "#94A3B8",
          accent: v("primary"),
          "accent-hover": v("primary-hover"),
          ink: v("brand-navy"),
        },
        apple: {
          blue: v("primary"),
          "blue-hover": v("primary-hover"),
          label: v("foreground"),
          secondary: v("muted-foreground"),
          tertiary: v("muted-foreground"),
          bg: v("background"),
          fill: v("surface-muted"),
          separator: v("border"),
        },
        ops: {
          bg: v("brand-navy"),
          surface: v("surface"),
          elevated: v("surface-muted"),
          label: v("foreground"),
          secondary: v("muted-foreground"),
          tertiary: v("muted-foreground"),
        },
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        apple: "1.25rem",
        "apple-lg": "1.75rem",
        "ui-sm": "var(--radius-sm)",
        "ui-md": "var(--radius-md)",
        "ui-lg": "var(--radius-lg)",
      },
      boxShadow: {
        "ui-sm": "var(--shadow-sm)",
        "ui-md": "var(--shadow-md)",
        "ui-lg": "var(--shadow-lg)",
        apple: "0 2px 8px rgba(0,0,0,0.04), 0 1px 2px rgba(0,0,0,0.06)",
        "apple-md": "0 4px 24px rgba(0,0,0,0.08), 0 2px 8px rgba(0,0,0,0.04)",
        "dashboard-card": "0 4px 6px -1px rgba(0,0,0,0.05), 0 2px 4px -2px rgba(0,0,0,0.04)",
        "dashboard-card-hover": "0 10px 15px -3px rgba(0,0,0,0.08), 0 4px 6px -4px rgba(0,0,0,0.05)",
        "ui-inset": "inset 0 1px 0 rgba(255,255,255,0.65)",
      },
      fontSize: {
        "2xs": ["12px", { lineHeight: "16px" }], // nhỏ nhất cho phép
        xs: ["12px", { lineHeight: "16px" }],
        sm13: ["13px", { lineHeight: "18px" }], // body bảng
        sm: ["14px", { lineHeight: "20px" }],
        base: ["16px", { lineHeight: "24px" }],
        lg: ["18px", { lineHeight: "26px" }],
        "2xl": ["24px", { lineHeight: "32px" }],
        "3xl": ["30px", { lineHeight: "36px" }],
      },
      height: {
        row: "var(--row-h-compact)",
        "row-touch": "var(--row-h-touch)",
        control: "var(--control-h)",
        "control-touch": "var(--control-h-touch)",
      },
      keyframes: {
        "tecsops-actions-strip": {
          "0%": { opacity: "0", transform: "translateY(-6px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "ui-toast-in": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "ui-skeleton": {
          "0%": { opacity: "0.45" },
          "50%": { opacity: "0.9" },
          "100%": { opacity: "0.45" },
        },
      },
      animation: {
        "tecsops-actions-strip": "tecsops-actions-strip 0.2s ease-out forwards",
        "ui-toast-in": "ui-toast-in 0.2s ease-out forwards",
        "ui-skeleton": "ui-skeleton 1.2s ease-in-out infinite",
      },
      transitionTimingFunction: {
        fluid: "cubic-bezier(0.16, 1, 0.3, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
    },
  },
  plugins: [],
};
