/**
 * ERROR_MONITOR_AGENT — hằng số, phân loại, quyền, sự kiện quan sát.
 * Không sửa mã nghiệp vụ. Không giấu lỗi. Không lưu secret.
 */

export const AGENT_NAME = "ERROR_MONITOR_AGENT";
export const SCHEMA_VERSION = "1.0.0";

export const ERROR_CLASSES = Object.freeze({
  SOFTWARE_ERROR: "SOFTWARE_ERROR",
  BUSINESS_VALIDATION: "BUSINESS_VALIDATION",
  USER_INPUT_ERROR: "USER_INPUT_ERROR",
  EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR",
  INFRASTRUCTURE_ERROR: "INFRASTRUCTURE_ERROR",
  AUTOMATION_ERROR: "AUTOMATION_ERROR",
  SECURITY_EVENT: "SECURITY_EVENT",
  UNKNOWN: "UNKNOWN",
});

/** Phân loại phụ cho automation (selector fail). */
export const AUTOMATION_SUBTYPES = Object.freeze({
  EXTERNAL_UI_CHANGE: "EXTERNAL_UI_CHANGE",
  OUR_CODE_BUG: "OUR_CODE_BUG",
  WORKFLOW_TIMEOUT: "WORKFLOW_TIMEOUT",
  EXT_PROTOCOL: "EXT_PROTOCOL",
});

export const SEVERITY = Object.freeze({
  SEV_0: "SEV-0",
  SEV_1: "SEV-1",
  SEV_2: "SEV-2",
  SEV_3: "SEV-3",
  SEV_4: "SEV-4",
});

export const INCIDENT_STATUS = Object.freeze({
  OPEN: "OPEN",
  DISPATCHED: "DISPATCHED",
  IN_PROGRESS: "IN_PROGRESS",
  FIXED_PENDING_OBSERVATION: "FIXED_PENDING_OBSERVATION",
  RESOLVED: "RESOLVED",
  REGRESSION: "REGRESSION",
  HUMAN_REVIEW_REQUIRED: "HUMAN_REVIEW_REQUIRED",
  SUPPRESSED_VALIDATION: "SUPPRESSED_VALIDATION",
});

export const HEALTH = Object.freeze({
  HEALTHY: "HEALTHY",
  DEGRADED: "DEGRADED",
  UNHEALTHY: "UNHEALTHY",
  UNKNOWN: "UNKNOWN",
});

export const HEALTH_COMPONENTS = Object.freeze([
  "frontend",
  "backend",
  "db",
  "workers",
  "automation",
]);

export const OBS_EVENTS = Object.freeze({
  ERROR_DETECTED: "ERROR_DETECTED",
  FINGERPRINT_CREATED: "FINGERPRINT_CREATED",
  INCIDENT_OPENED: "INCIDENT_OPENED",
  INCIDENT_UPDATED: "INCIDENT_UPDATED",
  BUG_DISPATCHED: "BUG_DISPATCHED",
  BUG_DISPATCH_SKIPPED: "BUG_DISPATCH_SKIPPED",
  FIX_RESULT_ACCEPTED: "FIX_RESULT_ACCEPTED",
  POST_FIX_OBSERVATION_STARTED: "POST_FIX_OBSERVATION_STARTED",
  REGRESSION_DETECTED: "REGRESSION_DETECTED",
  INCIDENT_RESOLVED: "INCIDENT_RESOLVED",
  HUMAN_REVIEW_REQUIRED: "HUMAN_REVIEW_REQUIRED",
  REPEATED_FIX_FAILURE: "REPEATED_FIX_FAILURE",
  WORKER_HEARTBEAT_LOST: "WORKER_HEARTBEAT_LOST",
  WORKER_RESTART_REQUESTED: "WORKER_RESTART_REQUESTED",
  WORKER_RESTART_EXHAUSTED: "WORKER_RESTART_EXHAUSTED",
  HEALTH_CHANGED: "HEALTH_CHANGED",
  SECRET_REDACTED: "SECRET_REDACTED",
  LLM_SKIPPED: "LLM_SKIPPED",
  LLM_CALLED: "LLM_CALLED",
  STORM_AGGREGATED: "STORM_AGGREGATED",
  RATE_LIMITED: "RATE_LIMITED",
  ESCALATED: "ESCALATED",
});

/** Lớp được phép bàn giao Bug Fix. Validation / user input / UI ngoài không gửi. */
export const DISPATCHABLE_CLASSES = Object.freeze(
  new Set([
    ERROR_CLASSES.SOFTWARE_ERROR,
    ERROR_CLASSES.INFRASTRUCTURE_ERROR,
    ERROR_CLASSES.AUTOMATION_ERROR,
    ERROR_CLASSES.SECURITY_EVENT,
    ERROR_CLASSES.UNKNOWN,
  ]),
);

export const NON_DISPATCHABLE_CLASSES = Object.freeze(
  new Set([
    ERROR_CLASSES.BUSINESS_VALIDATION,
    ERROR_CLASSES.USER_INPUT_ERROR,
    ERROR_CLASSES.EXTERNAL_SERVICE_ERROR,
  ]),
);

export const PERMISSIONS = Object.freeze({
  READ_LOGS: "READ_LOGS",
  READ_HEALTH: "READ_HEALTH",
  READ_DEPLOY_METADATA: "READ_DEPLOY_METADATA",
  CREATE_EVENT: "CREATE_EVENT",
  CREATE_INCIDENT: "CREATE_INCIDENT",
  CREATE_BUG_REPORT: "CREATE_BUG_REPORT",
  CREATE_NOTIFICATION: "CREATE_NOTIFICATION",
  EXECUTE_HEALTH_CHECK: "EXECUTE_HEALTH_CHECK",
  EXECUTE_SAFE_DIAGNOSTIC: "EXECUTE_SAFE_DIAGNOSTIC",
  EXECUTE_SCREENSHOT_TRACE: "EXECUTE_SCREENSHOT_TRACE",
  DENY_SOURCE_EDIT: "DENY_SOURCE_EDIT",
  DENY_PROD_DEPLOY: "DENY_PROD_DEPLOY",
  DENY_MIGRATION: "DENY_MIGRATION",
  DENY_DESTRUCTIVE_DB: "DENY_DESTRUCTIVE_DB",
  DENY_SECRET_CHANGE: "DENY_SECRET_CHANGE",
});

export const DENIED_ACTIONS = Object.freeze([
  PERMISSIONS.DENY_SOURCE_EDIT,
  PERMISSIONS.DENY_PROD_DEPLOY,
  PERMISSIONS.DENY_MIGRATION,
  PERMISSIONS.DENY_DESTRUCTIVE_DB,
  PERMISSIONS.DENY_SECRET_CHANGE,
]);

export const DEFAULTS = Object.freeze({
  observationWindowMs: 30 * 60 * 1000,
  correlationWindowMs: 5 * 60 * 1000,
  stormWindowMs: 10_000,
  stormThreshold: 200,
  llmMaxCallsPerWindow: 8,
  llmWindowMs: 60_000,
  dispatchCooldownMs: 15 * 60 * 1000,
  maxFixAttempts: 3,
  maxWorkerRestarts: 3,
  workerStaleMs: 45_000,
  maxStoredEventsPerIncident: 20,
  maxObservabilityEvents: 2_000,
  service: "tecsops",
});
